datasource:
  dbType: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
#  url: "postgresql://localhost:5432/postgres?sslmode=disable"
  username: "postgres"
  password: "1234"
  schema: "public"
server:
  port: 3000

  