// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID        int32
	UserID    pgtype.Int4
	Title     string
	Completed pgtype.Bool
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}
